### ISSUE TITLE
Getting Error in faceapp.php line 76 and 77

### ISSUE THREAD

**Issue by hi5blast** [NarimanMov/FaceApp-PHP#1]
Hi,

Iam getting error in faceapp.php line 76 and 77, No method or null error.
Is there any dependcies i need to install?

Thanks

**Comment by hi5blast** [comment]
Resolved

**Comment by NarimanMov** [comment]
Hi
You need to Upgrade your php to version >= 7.0
It will be work with php 7.0 or higher.

**Comment by hi5blast** [comment]
Yes it got resolved after upgrading to php 7,

Thank You :)

**Comment by powerisyour** [comment]
PHP Fatal error:  Uncaught Exception: Too many requests. Please try again later. in FaceApp-PHP-master/FaceApp/faceapp.php:68
