### ISSUE TITLE
faceapp.php:68

### ISSUE THREAD

**Issue by powerisyour** [NarimanMov/FaceApp-PHP#2]
Hi,

Iam getting error in faceapp.php line 68. 

 Error display like this : 

PHP Fatal error: Uncaught Exception: Too many requests. Please try again later. in FaceApp-PHP-master/FaceApp/faceapp.php:68

**Comment by NarimanMov** [comment]
Hi
This error is from faceapp servers
Because u have sent many requests
I prefer you to use proxy on php

**Comment by powerisyour** [comment]
how to use proxy on php any idea give me code

**Comment by NarimanMov** [comment]
finally proxy mode added to this project
take a look at 
https://github.com/NarimanMov/FaceApp-PHP/blob/master/test/RandomFilter.php
and README file for more informations
enjoy 🌹

**Comment by peter279k** [comment]
I think you should let the requests have the waiting time before sending the next request and it will avoid the two many requests problem.

**Comment by powerisyour** [comment]
if i have many traffic then what i do because so many people on my site and request on just one second many user send request on faceapp server .

**Comment by powerisyour** [comment]
Thank You for your big support .

Now one more question Is it possible to get direct image link url send on faceapp server istead of photo in own server

Example :
$FaceApp = new FaceApp('http://www.brandedgirls.com/wp-content/uploads/2015/11/Handsome-Arab-man-Udi-Karni1.jpg',true);

**Comment by NarimanMov** [comment]
You can download it to your server first
Then put the path in 
```new FaceApp(Downloaded_file_path , true)```

Maybe I'll add this feature to the next update

**Comment by cyb3rz** [comment]
@powerisyour  You cant try this  😄 
```
$userpic = 'http://www.brandedgirls.com/wp-content/uploads/2015/11/Handsome-Arab-man-Udi-Karni1.jpg';
file_put_contents("image.jpg" , fopen($userpic, "r"));
$FaceApp = new FaceApp("image.jpg");
```

**Comment by NarimanMov** [comment]
@cyb3rz Yes this is one of the ways! 🌹

**Comment by NarimanMov** [comment]
you wanna upload image from another url to the server
i don't know and didn't find any way to do this without saving that image....
