### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by cyb3rz** [NarimanMov/FaceApp-PHP#3]
Hello i juest added live proxy, but it showing "Unknown Error : 0"

**Comment by cyb3rz** [comment]
well its showing same error, 
i hava found another issue. some filters like "glasses" showing "Filter is not Free" when crop is true. make it false and then it works.

**Comment by NarimanMov** [comment]
i've checked proxies, they works fine
if you have problem with these HTTP Proxies check your internet connection

and about filters
as u saw 'glasses' filter with crop=false is not free
but 'glasses' filter with crop=true is free and works good

**Comment by Mauliko7** [comment]
I added a lot of proxy (all working) still it says "to many requests". on ProxyMode.php. i think it is using server ip even if proxy's  are added because it works fine on both the pages ProxyMode.phpl and on RandomFilter.php ) and it started giving "to many request"  on both page at same time even i added dedicated proxy's

**Comment by NarimanMov** [comment]
@Mauliko7 To be sure proxymode.php is working or not
Edit the faceapp.php
And change the curl address to http://jsonip.com and comment the "curl file" line
get the result and print it then use exit() to close the script
And check ip is changed or not
I've checked it and it worked fine but u check it too.

**Comment by NarimanMov** [comment]
@Mauliko7 man u were right...
proxy mode didn't work because of my mistake...
```
$this->PhotoOptions = $this->UploadPhoto($photo_path);
if ($turnOnProxy == true) {
       $this->setProxy();
 }
```
this code will active proxy after requesting...
and now fixed 💃 
```
if ($turnOnProxy == true) {
       $this->setProxy();
 }
$this->PhotoOptions = $this->UploadPhoto($photo_path);
```

tnx for reporting

**Comment by sajjad-amin** [comment]
it works in localhost. but when i uploaded in my server, this message showed " Default value for parameters with a class type hint can only be NULL in /home/sajjadam/public_html/faceapp/api/faceapp.php on line 22"
