### ISSUE TITLE
Too many requests. Please try again later.

### ISSUE THREAD

**Issue by troshan** [NarimanMov/FaceApp-PHP#6]
Why Im getting this? Is there any limitation?

**Comment by NarimanMov** [comment]
this service has some limits
so use "proxy mode" (look at test directory)

**Comment by Mauliko7** [comment]
how many request's can be made ? do you have any idea after how many request will get this error ?

**Comment by NarimanMov** [comment]
idk how many requests allowed but as i said use proxy mode to figure it out
