### ISSUE TITLE
image link not working

### ISSUE THREAD

**Issue by dhavalpadshala** [NarimanMov/FaceApp-PHP#7]
Hello,
script does Not working when i give link on image path.
 Actual code : 
    $FaceApp = new FaceApp("__DIR__.'/test/1.jpg'");
My Code: 
    $FaceApp = new FaceApp('https://i.imgur.com/aeuwLpOg.jpg');

**Comment by NarimanMov** [comment]
@dhavalpadshala It does not work with image url
U should download the image first
Then get the path of downloaded file and put it to the function

**Comment by dhavalpadshala** [comment]
There is another way to work with image url because i have high traffic website so download each user photo and put in to the function is make such load on my website.

**Comment by NarimanMov** [comment]
i don't have any idea to do that
if u found a way i like to know that 😄
